#!/bin/bash
# cram2bam 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    set -ex -o pipefail
    echo "Value of cram_in: '$cram_in'"
    echo "Value of crai_in_path: '$crai_in_path'"
    echo "Value of ref_fasta: '$ref_fasta'"
    echo "Value of ref_fai_path: '$ref_fai_path'"
    echo "Value of ref_fasta: '$region'"

    
    dx-download-all-inputs --parallel
    mv $crai_in_path /home/dnanexus/in/cram_in
    mv $ref_fai_path /home/dnanexus/in/ref_fasta
    bam_out="${cram_in_prefix}.${region}.bam"
	

    #/usr/bin/samtools_helper.sh $ref_fasta_path $cram_in_path $bam_out $region
    /usr/bin/samtools view -@16 -b -T $ref_fasta_path -o $bam_out $cram_in_path $region
    /usr/bin/samtools index $bam_out;


    bam=$(dx upload $bam_out --brief)
    bai=$(dx upload $bam_out.bai --brief)
   
    dx-jobutil-add-output bam "$bam" --class=file
    dx-jobutil-add-output bai "$bai" --class=file
}