#!/bin/bash
# bcftools_extract_tumor 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    echo "Value of vcf: '$vcf'"
    echo "Value of vcf_index: '$vcf_index'"
    echo "Value of multiallelic: '$multiallelic'"
    echo "Value of output_type: '$output_type'"
    echo "Value of output_name: '$output_name'"
    echo "Value of dockerimage_bcftools: '$dockerimage_bcftools'"

    dx-download-all-inputs --parallel
    mv $vcf_index_path ~/in/vcf

    docker load -i $dockerimage_bcftools_path
    docker run --rm -v /home/dnanexus:/home/dnanexus -v /mnt/UKBB_Exome_2021:/mnt/UKBB_Exome_2021 -w /home/dnanexus kboltonlab/sam_bcftools_tabix_bgzip:1.0 \
        /bin/bash -c "/usr/local/bin/bcftools norm -m ${multiallelic} -O${output_type} -o ${tumor_sample_name}.${output_name} ${vcf_path} --threads 8 && /usr/local/bin/tabix ${tumor_sample_name}.${output_name}"


    normalized_vcf=$(dx upload ${tumor_sample_name}.${output_name} --brief)
    normalized_vcf_index=$(dx upload ${tumor_sample_name}.${output_name}.tbi --brief)

    dx-jobutil-add-output normalized_vcf "$normalized_vcf" --class=file
    dx-jobutil-add-output normalized_vcf_index "$normalized_vcf_index" --class=file

}
