#!/bin/bash
# cram2bam 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    set -ex -o pipefail 

    echo $bam_in1_path
    echo $bai_in1_path
    echo $bam_in2_path
    echo $bam_in1_path
    echo $bam_in1_name 
    echo $bam_in2_name
    

    dx-download-all-inputs --parallel
 
    mv $bam_in1_path .
    mv $bai_in1_path .
    mv $bam_in2_path .
    mv $bai_in2_path .

	/usr/bin/samtools merge -@ 16 $out_name.bam $bam_in1_name $bam_in2_name
    /usr/bin/samtools index $out_name.bam
    mv ${out_name}.bam.bai ${out_name}.bai

    bam_out=$(dx upload ${out_name}.bam --brief)
    bai_out=$(dx upload ${out_name}.bai --brief)
    
    dx-jobutil-add-output bam_out "$bam_out" --class=file
    dx-jobutil-add-output bai_out "$bai_out" --class=file

}