#!/bin/bash
# bcftools_extract_tumor 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    set -ex -o pipefail

    echo "Value of uuid: '$uuid'"
    echo "Value of token_file: '$token_file'"
    echo "Value of token_file_path: '$token_file_path'"

    dx-download-all-inputs --parallel
    chmod 600 $token_file_path
    /gdc-client download $uuid -t $token_file_path -n16
    cd $uuid

    bam=$(dx upload *.bam --brief)
    bai=$(dx upload *.bai --brief)

    dx-jobutil-add-output bam "$bam" --class=file
    dx-jobutil-add-output bai "$bai" --class=file

}
