#!/bin/bash
# cram2bam 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    set -ex -o pipefail
    echo "Value of folder: '$folder_in'"
    echo "Value of folder_name: '$folder_name'"
    echo "Value of tar_name: '$tar_name'"

    ls /environment
    ls /mnt
    which multiqc
    multiqc project-G3Yj1vjJ6XG579jbKyjXPGGY:/CH_Exome/Workflow_Outputs/FINAL/Alignment_QC/12

    dx download --no-progress -r --lightweight $folder_in -f
    ls $folder_name | wc -l
    # tar -czvf msk.pileup.59.tar.gz 59
    tar -czvf $tar_name $folder_name
    
    # dx upload msk.pileup.59.tar.gz --destination project-G3Yj1vjJ6XG579jbKyjXPGGY:/CH_Exome/Workflow_Outputs/FINAL/MSK_Pileup/
    tar_out=$(dx upload "$tar_name" --brief)
    dx-jobutil-add-output tar_out --class=file "$tar_out"
}