#!/bin/bash
# cram2bam 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of cram_in: '$cram_in'"
    echo "Value of ref_fasta: '$ref_fasta'"

    dx-download-all-inputs --parallel
 
    bam_out="${cram_in_prefix}.bam"
	
    #docker load -i $samtools_path # path to samtools docker
    # docker run --rm -v /home/dnanexus:/home/dnanexus -v /mnt/UKBB_Exome_2021:/mnt/UKBB_Exome_2021 -v /usr/bin:/usr/bin -w /home/dnanexus quay.io/biocontainers/samtools:1.11--h6270b1f_0 /usr/bin/cram2bam_helper.sh $ref_fasta_path $cram_in_path $bam_out
    /usr/bin/cram2bam_helper.sh $ref_fasta_path $cram_in_path $bam_out
    
    bai_out=$(dx upload ${bam_out}.bai --brief)
    bam_out=$(dx upload $bam_out --brief)
   
    dx-jobutil-add-output bam_out "$bam_out" --class=file
    dx-jobutil-add-output bai_out "$bai_out" --class=file
    dx-jobutil-add-output sample_name "$sample_name" --class=string
}