#!/bin/bash
# bcftools_extract_tumor 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    echo "Value of vcf: '$vcf'"
    echo "Value of vcf_index: '$vcf_index'"
    echo "Value of region: '$region'"
    echo "Value of output_type: '$output_type'"
    echo "Value of output_name: '$output_name'"
    echo "Value of dockerimage_bcftools: '$dockerimage_bcftools'"
 
    # dx run applet-GGV85p0J6XGGvXqV682k2kjG -ivcf=file-G56pG88JykJqQjF64xxqXgJK -ivcf_index=file-G56pFvjJykJj714F4qqxvxJq -iregion="chrX:48683823-48794079" --destination $NEW_EXOME:/Brian/test/ -y

    dx-download-all-inputs --parallel
    mv $vcf_index_path ~/in/vcf

    docker load -i $dockerimage_bcftools_path
    docker run --rm -v /home/dnanexus:/home/dnanexus -v /mnt/UKBB_Exome_2021:/mnt/UKBB_Exome_2021 -w /home/dnanexus kboltonlab/sam_bcftools_tabix_bgzip:1.0 \
        /bin/bash -c "/usr/local/bin/bcftools view -O${output_type} -o ${output_name} ${vcf_path} --threads 8 $region && /usr/local/bin/tabix ${output_name}"


    filtered_vcf=$(dx upload ${output_name} --brief)
    filtered_vcf_index=$(dx upload ${output_name}.tbi --brief)

    dx-jobutil-add-output filtered_vcf "$filtered_vcf" --class=file
    dx-jobutil-add-output filtered_vcf_index "$filtered_vcf_index" --class=file

}
